"use client";
import { useState } from "react";
import { CheckCircle2, Download, LoaderCircle, ShieldCheck, Trash2 } from "lucide-react";
import { AlertDialog, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { DELETE_ACCOUNT_CONFIRMATION } from "@/lib/account/validation";
import { APP_VERSION } from "@/lib/app-version";
import type { Locale } from "@/lib/shelf-seasons";
const copy = {
  en: { title: "Your data", exportTitle: "Download your data", exportLead: "Save your books, reading history, goals, series and recap choices as a JSON file.", export: "Download JSON", exporting: "Preparing…", exported: "Your export is ready.", exportError: "The export could not be created. Please try again.", privacy: "The export contains your private reading data. Custom cover image files are not embedded.", danger: "Delete account", deleteLead: "Permanently remove your Shelf Seasons account, books, covers and reading history.", delete: "Delete my account", dialogTitle: "Delete everything permanently?", dialogLead: "This cannot be undone. Download your data first if you want to keep a copy.", typeLabel: "Type Shelf Seasons to confirm", confirm: "Delete everything", cancel: "Keep my account", deleting: "Deleting…", deleteError: "Account deletion could not be completed. Please try again.", version: "App version" },
  ru: { title: "Твои данные", exportTitle: "Скачать свои данные", exportLead: "Сохрани книги, историю чтения, цели, серии и выбранные итоги в одном JSON-файле.", export: "Скачать JSON", exporting: "Готовим файл…", exported: "Файл с данными готов.", exportError: "Не удалось подготовить файл. Попробуй ещё раз.", privacy: "В файле будут приватные данные о чтении. Сами изображения пользовательских обложек в него не включаются.", danger: "Удаление аккаунта", deleteLead: "Навсегда удалить аккаунт Shelf Seasons, книги, обложки и всю историю чтения.", delete: "Удалить мой аккаунт", dialogTitle: "Удалить всё навсегда?", dialogLead: "Отменить это действие нельзя. Если хочешь сохранить историю, сначала скачай свои данные.", typeLabel: "Для подтверждения введи Shelf Seasons", confirm: "Удалить всё", cancel: "Оставить аккаунт", deleting: "Удаляем…", deleteError: "Не удалось завершить удаление аккаунта. Попробуй ещё раз.", version: "Версия приложения" },
} as const satisfies Record<Locale, Record<string, string>>;
export function AccountControls({ locale }: { locale: Locale }) {
  const c = copy[locale]; const [exportState, setExportState] = useState<"idle" | "pending" | "success" | "error">("idle"); const [dialogOpen, setDialogOpen] = useState(false); const [confirmation, setConfirmation] = useState(""); const [deleting, setDeleting] = useState(false); const [deleteError, setDeleteError] = useState(false);
  async function downloadExport() { setExportState("pending"); try { const response = await fetch("/api/account/export", { cache: "no-store" }); if (!response.ok) throw new Error(); const blob = await response.blob(); const disposition = response.headers.get("content-disposition") ?? ""; const filename = disposition.match(/filename="([^"]+)"/)?.[1] ?? "shelf-seasons-export.json"; const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; document.body.append(link); link.click(); link.remove(); URL.revokeObjectURL(url); setExportState("success"); } catch { setExportState("error"); } }
  async function deleteAccount() { if (confirmation !== DELETE_ACCOUNT_CONFIRMATION) return; setDeleting(true); setDeleteError(false); try { const response = await fetch("/api/account/delete", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ confirmation }) }); if (!response.ok) throw new Error(); window.location.replace(`/${locale}/sign-in?deleted=1`); } catch { setDeleteError(true); setDeleting(false); } }
  return <section className="account-controls"><h2>{c.title}</h2><div className="account-action"><span className="setting-icon"><Download /></span><div><strong>{c.exportTitle}</strong><p>{c.exportLead}</p></div><Button type="button" variant="outline" onClick={downloadExport} disabled={exportState === "pending"}>{exportState === "pending" && <LoaderCircle className="route-spinner" />}{exportState === "pending" ? c.exporting : c.export}</Button></div>{exportState === "success" && <p className="account-success" role="status"><CheckCircle2 />{c.exported}</p>}{exportState === "error" && <p className="form-error" role="alert">{c.exportError}</p>}<p className="account-privacy"><ShieldCheck />{c.privacy}</p><div className="account-action account-danger"><span className="setting-icon"><Trash2 /></span><div><strong>{c.danger}</strong><p>{c.deleteLead}</p></div><AlertDialog open={dialogOpen} onOpenChange={(open) => { if (!deleting) { setDialogOpen(open); if (!open) { setConfirmation(""); setDeleteError(false); } } }}><AlertDialogTrigger asChild><Button type="button" variant="outline" className="danger-button">{c.delete}</Button></AlertDialogTrigger><AlertDialogContent className="delete-account-dialog"><AlertDialogHeader><AlertDialogTitle>{c.dialogTitle}</AlertDialogTitle><AlertDialogDescription>{c.dialogLead}</AlertDialogDescription></AlertDialogHeader><label><span>{c.typeLabel}</span><input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="off" disabled={deleting} /></label>{deleteError && <p className="form-error" role="alert">{c.deleteError}</p>}<AlertDialogFooter><AlertDialogCancel disabled={deleting}>{c.cancel}</AlertDialogCancel><Button type="button" variant="destructive" onClick={deleteAccount} disabled={deleting || confirmation !== DELETE_ACCOUNT_CONFIRMATION}>{deleting && <LoaderCircle className="route-spinner" />}{deleting ? c.deleting : c.confirm}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog></div><p className="app-version">{c.version}: {APP_VERSION}</p></section>;
}
