import type { Locale } from "@/lib/shelf-seasons";

export const authCopy = {
  en: {
    signInEyebrow: "Your personal reading journal",
    signInTitle: "Welcome to Shelf Seasons",
    signInLead:
      "Keep your shelves, reading days and yearly memories together — privately and across devices.",
    google: "Continue with Google",
    googlePending: "Opening Google…",
    privacy: "Only your basic Google profile is used to create your account.",
    setupTitle: "Connect Supabase to enable accounts",
    setupLead:
      "The interface is still available in demo mode. Add the development project values to .env.local when you are ready to test sign-in.",
    openDemo: "Open demo",
    authError: "Sign-in did not finish. Nothing was changed — please try again.",
    callbackTitle: "Opening your library",
    callbackLead: "Google sign-in is complete. Your private session is being saved…",
    callbackErrorTitle: "Sign-in needs another try",
    onboardingEyebrow: "A few quiet choices",
    onboardingTitle: "Make this library yours",
    onboardingLead: "You can change every setting later.",
    locale: "Language",
    timezone: "Timezone",
    theme: "Appearance",
    system: "Use device setting",
    light: "Light",
    dark: "Dark",
    goal: "Reading goal for this year",
    goalHint: "Optional · 1–999 books",
    finish: "Enter my library",
    onboardingError: "We could not save these settings. Check the fields and try again.",
    account: "Account",
    connected: "Your profile and preferences are saved securely.",
    signOut: "Sign out",
  },
  ru: {
    signInEyebrow: "Личный дневник чтения",
    signInTitle: "Добро пожаловать в Shelf Seasons",
    signInLead:
      "Полки, дни чтения и книжные воспоминания сохраняются приватно и доступны на разных устройствах.",
    google: "Продолжить с Google",
    googlePending: "Открываем Google…",
    privacy: "Для создания аккаунта используется только основная информация профиля Google.",
    setupTitle: "Подключи Supabase, чтобы включить аккаунты",
    setupLead:
      "Интерфейс по-прежнему доступен в деморежиме. Для проверки входа добавь данные dev-проекта в .env.local.",
    openDemo: "Открыть демоверсию",
    authError: "Вход не завершился. Ничего не изменилось — попробуй ещё раз.",
    callbackTitle: "Открываем твою библиотеку",
    callbackLead: "Вход через Google завершён. Сохраняем защищённую сессию…",
    callbackErrorTitle: "Нужно повторить вход",
    onboardingEyebrow: "Несколько спокойных настроек",
    onboardingTitle: "Настрой библиотеку под себя",
    onboardingLead: "Все параметры можно изменить позже.",
    locale: "Язык",
    timezone: "Часовой пояс",
    theme: "Оформление",
    system: "Как на устройстве",
    light: "Светлое",
    dark: "Тёмное",
    goal: "Цель по чтению на этот год",
    goalHint: "Необязательно · от 1 до 999 книг",
    finish: "Перейти в библиотеку",
    onboardingError: "Не получилось сохранить настройки. Проверь поля и попробуй ещё раз.",
    account: "Аккаунт",
    connected: "Профиль и настройки сохраняются безопасно.",
    signOut: "Выйти",
  },
} as const satisfies Record<Locale, Record<string, string>>;
